#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]

mod errors;
pub use errors::*;

include!(concat!(env!("OUT_DIR"), "/bindings.rs")); // file generated by bindgen

#[derive(Copy, Clone)]
pub struct FmodSystem {
    pub ptr: *mut FMOD_SYSTEM,
    _not_sync: std::marker::PhantomData<*mut ()>,
}

impl FmodSystem {
    pub fn new(ptr: *mut FMOD_SYSTEM) -> Self {
        Self {
            ptr,
            _not_sync: std::marker::PhantomData,
        }
    }

    pub fn as_ptr(&self) -> *mut FMOD_SYSTEM {
        self.ptr
    }
}

impl std::ops::Deref for FmodSystem {
    type Target = *mut FMOD_SYSTEM;

    fn deref(&self) -> &Self::Target {
        &self.ptr
    }
}

impl std::ops::DerefMut for FmodSystem {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.ptr
    }
}

unsafe impl Send for FmodSystem {}
